In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('dataset/STUDENT.csv')
df.head()

review  age gender  education purchased  grade
0  Average   16      F  Undergrad       Yes    NaN
1     Good   21      M       Grad        No   85.0
2     Good   23      M       Grad        No   78.0
3     Poor   30      F        PhD        No    NaN
4     Best   19      F  Undergrad       Yes   92.0

In [3]:
df['purchased'].value_counts()

purchased
Yes    5
No     5
Name: count, dtype: int64

In [4]:
df['grade']

0     NaN
1    85.0
2    78.0
3     NaN
4    92.0
5    88.0
6    76.0
7    95.0
8     NaN
9    80.0
Name: grade, dtype: float64

In [5]:
df.isnull().sum()

review       0
age          0
gender       0
education    0
purchased    0
grade        3
dtype: int64

In [36]:
data=df

In [37]:
data

review  age gender  education purchased  grade
0  Average   16      F  Undergrad       Yes    NaN
1     Good   21      M       Grad        No   85.0
2     Good   23      M       Grad        No   78.0
3     Poor   30      F        PhD        No    NaN
4     Best   19      F  Undergrad       Yes   92.0
5     Poor   22      M        PhD       Yes   88.0
6  Average   25      M       Grad        No   76.0
7     Best   18      F  Undergrad       Yes   95.0
8  Average   20      F        PhD       Yes    NaN
9     Best   24      M       Grad        No   80.0

In [7]:
from sklearn.model_selection import train_test_split

In [38]:
X_train,X_test,y_train,y_test=train_test_split(data.loc[:,['review','gender','education','grade','age']],data.loc[:,['purchased']],test_size=0.2)

In [39]:
X_train

review gender  education  grade  age
4     Best      F  Undergrad   92.0   19
3     Poor      F        PhD    NaN   30
1     Good      M       Grad   85.0   21
6  Average      M       Grad   76.0   25
8  Average      F        PhD    NaN   20
9     Best      M       Grad   80.0   24
5     Poor      M        PhD   88.0   22
2     Good      M       Grad   78.0   23

In [40]:
y_train

purchased
4       Yes
3        No
1        No
6        No
8       Yes
9        No
5       Yes
2        No

 # 1.Aam Zindagi

In [41]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [42]:
# adding simple imputer to grade col ( to remove NAN value is default is mean)
si=SimpleImputer()
X_train_grade=si.fit_transform(X_train[['grade']])

# also the test data
X_test_grade=si.fit_transform(X_test[['grade']])

In [43]:
X_train_grade

array([[92.        ],
       [83.16666667],
       [85.        ],
       [76.        ],
       [83.16666667],
       [80.        ],
       [88.        ],
       [78.        ]])

In [44]:
X_test_grade.shape

(2, 1)

In [47]:
# OrdinalEncoding -- > review 
oe=OrdinalEncoder(categories=[['Poor','Good','Average','Best']])
X_train_review=oe.fit_transform(X_train[['review']])

# also the test data
X_test_review=oe.fit_transform(X_test[['review']])

In [48]:
X_train_review.shape

(8, 1)

In [63]:
# OneGHotEncoding 
ohe=OneHotEncoder(drop='first')
X_train_gender=ohe.fit_transform(X_train[['gender']])

# also the test data
X_test_gender=ohe.fit_transform(X_test[['gender']])
X_train_gender.toarray()


 # for education columns
X_train_education=ohe.fit_transform(X_train[['education']])

# alse test data
X_test_education=ohe.fit_transform(X_test[['education']])
X_train_education.toarray()

array([[0., 1.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.]])

In [73]:
X_train_gender.shape

(8, 1)

In [74]:
X_train_education.shape

(8, 2)

In [66]:
X_train

review gender  education  grade  age
4     Best      F  Undergrad   92.0   19
3     Poor      F        PhD    NaN   30
1     Good      M       Grad   85.0   21
6  Average      M       Grad   76.0   25
8  Average      F        PhD    NaN   20
9     Best      M       Grad   80.0   24
5     Poor      M        PhD   88.0   22
2     Good      M       Grad   78.0   23

In [67]:
# Extracting Age
X_train_age=X_train.drop(columns=['review','gender','education','grade']).values

#also test data
X_test_age=X_test.drop(columns=['review','gender','education','grade']).values

In [68]:
X_train_age.shape

(8, 1)

# Error Not Concatenate Not same Dimension

In [78]:
X_train_Transformed=np.concatenate((X_train_age,X_train_review,X_train_grade,X_train_gender),axis=1)

# also test data
X_test_Transformed=np.concatenate((X_test_age,X_test_review,X_train_grade,X_test_gender),axis=1)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 3 has 0 dimension(s)

# Mentos Zindagi

# Using Column-Transformer

In [79]:
from sklearn.compose import ColumnTransformer

In [83]:
transformer=ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['grade']),
    ('tnf2',OrdinalEncoder(categories=[['Poor','Good','Average','Best']]),['review']),
    ('tnf3',OneHotEncoder(drop='first'),['gender','education'])
],remainder='passthrough')

In [98]:
d=transformer.fit_transform(X_train).astype(int)
d

array([[92,  3,  0,  0,  1, 19],
       [83,  0,  0,  1,  0, 30],
       [85,  1,  1,  0,  0, 21],
       [76,  2,  1,  0,  0, 25],
       [83,  2,  0,  1,  0, 20],
       [80,  3,  1,  0,  0, 24],
       [88,  0,  1,  1,  0, 22],
       [78,  1,  1,  0,  0, 23]])

In [93]:
transformer.fit_transform(X_test)

array([[95.,  3., 18.],
       [95.,  2., 16.]])